parking_app_23f2005464/controllers/authentication.py
from flask import Blueprint, request, jsonify,redirect,url_for,flash,render_template,session
from models.model import *
from passlib.hash import bcrypt
from sqlalchemy import text
from controllers.admin import admin_session,user_session

auth_bp= Blueprint('auth', __name__, url_prefix='/')

@auth_bp.route('/login_db', methods=['POST']) #endpoint url 
def login():     #endpoint name 
    if request.method=='POST':
      email=request.form['Email']
      pwd=request.form['password']
      user=User.query.filter_by(email=email).first()
      if user and bcrypt.verify(pwd,user.password):  
        session['user_id']=user.email  
        return redirect(url_for("home"))
    
      admin=Admin.query.filter_by(email=email,password=pwd).first()
      if admin and pwd==admin.password: 
          session['admin_id']=admin.email
          return redirect(url_for("admin.query")) #add_lot.query is admin_home rendering function
          
      else :
          return  render_template('error.html',message="No user Found",redirect_url=url_for("login"))

          
          
@auth_bp.route('/create_user',methods=['POST'])
def create_user():
    if request.method=='POST':
        print("user.create_user func intialized")
        email=request.form['Email']
        print(email)
        password=request.form['password']
        Full_name=request.form['Full name']
        Address =request.form['Address']
        pincode=request.form['pincode']
        print(pincode)
        
        exist_user=User.query.filter_by(email=email).first()
        if exist_user:
            flash('User with this email already exists.', 'error')
            return render_template("register.html")
        else: 
          db.session.add(User(email=email,password=bcrypt.hash(password),Full_Name=Full_name,Address=Address,Pincode=pincode))
          db.session.commit()          
          return render_template('success.html',message='Registered Successfully',redirect_url=url_for('login'))


@auth_bp.route('admin/logout' ,methods=['GET'])
def logout():
    try:
        admin = admin_session()
        user = user_session()

        if admin and admin.id:
            db.session.execute(text('''
                DELETE FROM parking_spots
                WHERE lot_id IN (
                    SELECT id FROM parking_lots WHERE admin_id = :admin_id
                ) AND status = 'I'
            '''), {"admin_id": admin.id})
            db.session.commit()
            session.clear()
            print("log :: admin logged out successfully")
            # flash("Logged out successfully.")
            return  render_template('successfull.html',message="Logged out successfully",redirect_url=url_for("login"))

        elif user:
            session.clear()
            print("log :: user logged out")
            return  render_template('successfull.html',message="Logged out successfully",redirect_url=url_for("login"))

        # flash("No user/admin session found.")
        return  render_template('successfull.html',message="No user/admin session found.",redirect_url=url_for("login"))

    except Exception as e:
        print("log :: exception in logout:", e)
        return redirect(url_for("login"))

@auth_bp.route('forgot_pwd',methods=['GET','POST'])
def forgot_pwd():
    if request.method=='GET':
          print("user.forgot_pwd intialized as get and rendered html")
          return render_template('forgot_pwd.html')
    if request.method=='POST':
        print("user.forgot_pwd intialized")
        email=request.form['Email']
        Full_Name=request.form['Full_name']
        new_password=request.form['new_pwd'] 
        user=User.query.filter_by(email=email,Full_Name=Full_Name).first()
        if user and bcrypt.verify(new_password,user.password):
            return  render_template('error.html',message="Previous password cannot be updated!",redirect_url=url_for('login')) 
        if user :
            user.password=bcrypt.hash(new_password)
            db.session.commit()
            return render_template('success.html',message="Password Updated",redirect_url=url_for('login'))
        else : 
            return render_template('error.html',message="User Not Found!",redirect_url=url_for('auth.forgot_pwd'))    
        

parking_app_23f2005464/controllers/user.py
from flask import Blueprint,request,render_template,flash,redirect,url_for
from sqlalchemy import text
from models.model import * 
from controllers.admin import user_session,paying_hrs,get_ist_now,hr_calc
from datetime import datetime,timezone
user_bp=Blueprint('user',__name__,url_prefix="/user")




@user_bp.route("/search_lots",methods=['POST','GET'])
def search_lots():
    pincode=request.form.get('pincode')
    user_id=user_session()
    print(pincode)
    lots=Parking_lot.query.filter_by(Pincode=pincode).all() 
    if not lots:
        return render_template('error.html',message="parking lot not found in your area",redirect_url=url_for('home'))
    
    result=[]
    
    # available_spots=
    for lot in lots:
        available_spots= db.session.execute(
                   text('SELECT COUNT(id) AS available_spots FROM parking_spots WHERE lot_id=:lot_id AND status="A"'),
                   {"lot_id": lot.id}
                    ).scalar()
        result.append({
            "id":lot.id,
            "Address":lot.Address,
            "Available_spots":available_spots,
            "price":lot.price_per_hour_of_spot,
        })

    history=Reserve_parking_spot.query.filter_by(user_id=str(user_id.id)).all()    
    return render_template("home.html", lots=result, searched_pincode=pincode,user_id=user_id,reserves=history,get_ist_now=get_ist_now,paying_hrs=paying_hrs,Searched_flag=True)   


@user_bp.route('users_data',methods=['GET'])
def users_data():
   users_data=db.session.execute(text("Select * from users"))
   print(users_data)
   users=[]
   for user in users_data:
       users.append({
           "user_id":user.id,
           "email":user.email,
           "Name":user.Full_Name,
           "Address":user.Address,
           "Pincode":user.Pincode,
       })
   return render_template('users_data.html',users=users)

#------------------------------------------------------------View profile------------------------------------------------------->
@user_bp.route('view_profile',methods=['GET'])
def user_profile():
    print("log :: profile view automatically")
    data=user_session()#automatically get user_id from session
    print(data.email)
    print(data.id)
    return render_template('edit_profile_user.html',user=data)
   
@user_bp.route('user_edit/<int:user_id>',methods=['POST'])
def user_edit(user_id):
     print("log ::  edit requested")
     print(f"form data request {request.form.get('Name')} ,Address: {request.form.get('Address')} , Pincode : {request.form.get('Pincode')}")  
   
     db.session.execute(text('''UPDATE users SET Full_Name=:Name,
                                                 Address=:Address ,
                                                 Pincode=:Pincode 
                             where email=:email '''),
                                           {

                                               "Name":request.form.get('Name'),
                                               "Address":request.form.get('Address'),
                                               "Pincode":request.form.get('Pincode'),
                                               "email":request.form.get('email')
                                           }                        
                                           
                                            )
     db.session.commit()
     
     return render_template('success.html',message="Profile updated successfully",redirect_url=url_for('user.user_profile'))
 
# reservation logic
@user_bp.route('/booking/<int:lot_id>')
def booking_spot_form(lot_id):
    id_allocationing=db.session.execute(text(''' Select id from parking_spots where lot_id=:lot_id and status=:status LIMIT 1 '''),{"lot_id":lot_id,"status":'A'}).fetchone()
    if id_allocationing is None:
        return render_template('error.html',message='Spot is Not Available!',redirect_url=url_for('home'))
   
    return render_template('booking_form.html',lot_id=lot_id,user_id=user_session().id, spot_id=id_allocationing[0])


@user_bp.route('/booking/<string:user_id>/<string:spot_id>',methods=['POST'])
def reserving(user_id,spot_id):
    db.session.execute(text(''' UPDATE parking_spots SET status='O' WHERE id=:spot_id '''),{"spot_id":spot_id})
    
    # spot status not required to check bcoz booking spot func logic already give only A spots
    
    #for confirmation lets check if user already reserved? bcoz if user hinder the load or alter url
    exist_reservation=Reserve_parking_spot.query.filter_by(user_id=user_id,spot_id=spot_id).filter(Reserve_parking_spot.end_parking_timestamp.is_(None)).first()
    if exist_reservation:
        return render_template('error.html',message='Spot Already reserved by you',redirect_url=url_for('home'))
    
    
    db.session.execute(text(''' INSERT INTO reserve_parking_spot (user_id,spot_id,parking_timestamp,Total_amount_user_paid,vehicle_number,end_parking_timestamp)
                                VALUES (:user_id,:spot_id,CURRENT_TIMESTAMP,:total_amt,:vehicle_no,:end_parking_stamp)'''),{"spot_id":spot_id,"user_id":user_id,"vehicle_no":request.form['vehicle_no'],"total_amt":0,"end_parking_stamp":None})
    db.session.commit()
    
    return render_template("success.html",message="Booked spot successfully",redirect_url=url_for('home'))

@user_bp.route('/history/release/<string:spot_id>',methods=['GET','POST'])
def release_and_payment(spot_id):
  
    if request.method=='GET':
        current_timestamp = datetime.now(timezone.utc)  #utc=coordinated universal time
        Data=db.session.query(Reserve_parking_spot,Parking_lot,Parking_spot).join(Parking_spot,Reserve_parking_spot.spot_id==Parking_spot.id).join(Parking_lot,Parking_spot.lot_id==Parking_lot.id).filter(Reserve_parking_spot.spot_id==spot_id).filter(Reserve_parking_spot.end_parking_timestamp==None).first()
        reserve,lot,spot=Data
        print(reserve.parking_timestamp.replace(tzinfo=timezone.utc))
        parking_timestamp=reserve.parking_timestamp
        userdata=User.query.filter_by(id=user_session().id).first()
        name=userdata.Full_Name
        email=userdata.email
        duration=hr_calc(current_timestamp,parking_timestamp)
        total_amt=int(duration)*int(lot.price_per_hour_of_spot)
        print(f"log:: func release_add_payment , {name} parked for duration {duration} has total amount {total_amt}***********")
        return render_template('payment.html',name=name,email=email,parking_timestamp=parking_timestamp,current_timestamp=current_timestamp,duration=duration,spot_id=spot_id,get_ist_now=get_ist_now,total_amt=float(total_amt))
   
   
   
   
    if request.method=='POST':
            current_timestamp=request.form['utc_now']
            total_amt=request.form['total_amt']
            hrs=request.form['hrs']
            db.session.execute(text('''
                    UPDATE reserve_parking_spot
                    SET end_parking_timestamp = :current_timestamp , duration =:hrs,Total_amount_user_paid=:Total_amt
                    WHERE user_id = :user_id AND spot_id = :spot_id AND end_parking_timestamp IS NULL
                '''), {
                    "user_id": user_session().id,
                    "spot_id": spot_id,
                    "current_timestamp":current_timestamp,
                    "hrs":hrs,
                    "Total_amt":total_amt
                })
                    
            
            db.session.execute(text('''UPDATE parking_spots SET status='A' WHERE id=:spot_id'''),{"spot_id":spot_id})
            db.session.commit()
            return render_template('success.html',message=f"Successfully Paid Amount {total_amt} ",redirect_url=url_for('home'))

@user_bp.route('/user_summary', methods=['GET', 'POST'])
def user_summary():
    print("log :: user summary initialized")
    user_id = user_session().id
    #this below query will do filter with join reserveparking spot ,parking spot and parking lot filter by userid and active users 
    query = db.session.query(Reserve_parking_spot, Parking_spot, Parking_lot
    ).join(Parking_spot, Reserve_parking_spot.spot_id == Parking_spot.id
    ).join(Parking_lot, Parking_spot.lot_id == Parking_lot.id
    ).filter(
        Reserve_parking_spot.user_id == user_id,
        Reserve_parking_spot.end_parking_timestamp == None
    ).all()

    current_timestamp = datetime.now(timezone.utc)
    durations = []
    counts_loc = {}

    aggregated_durations = {}
    #data processing for list of dic 
    for res, ps, pl in query:
        parking_timestamp = res.parking_timestamp
        duration = hr_calc(current_time=current_timestamp, parking_time=parking_timestamp)

        counts_loc[pl.prime_location] = counts_loc.get(pl.prime_location, 0) + 1

        if pl.prime_location not in aggregated_durations:
            aggregated_durations[pl.prime_location] = {
                "total_duration": duration,
                "spots": [{"spot_id": ps.id ,"duration":duration}]
            }
        else:
            aggregated_durations[pl.prime_location]["total_duration"] += duration
            aggregated_durations[pl.prime_location]["spots"].append(
                {"spot_id": ps.id,"duration":duration}
            )
    for loc,values in aggregated_durations.items():
        durations.append({
        "prime_location": loc,
        "total_duration": values["total_duration"],
        "spots": values["spots"]
    })
    
    print("completed")
    return render_template('user_summary.html', data=durations, count_loc=counts_loc)

parking_app_23f2005464/templates/booking_form.html
<!DOCTYPE html>
<!DOCTYPE html>
<html>

<head>
    <title>Admin</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Londrina+Solid&display=swap">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
        rel="stylesheet">
    <style>
        .custom-navbar {
            background-color: #D9D9D9; 
            font-family: "Inter", sans-serif;
        }

        .navbar-brand {
            color: black;
            margin-left: 1rem;
        }

        .navbar-nav {
            display: flex;
            justify-content: center;
            gap: 1rem;
            font-size: larger;
            margin-left: auto;
        }

        .nav-item.nav-link {
            padding-left: 50px !important;
        }

        .btn-primary {
    background: black;
    border-color: black;
    margin-left: auto;
    margin-right: 1rem;
}

.btn-primary:hover {
    background-color: #048002;
    border-color: #222831;
}


        .container {
            height: fit-content;
            justify-content: center;
            border-style: solid;
            border-color: black;
            border-radius: 20px;
            margin-top: 2rem;
            text-align: center;
            overflow-y: auto;
            scrollbar-width: none;
        }

        .form-text {
            display: flex-box;
            max-width: max-content;
            padding-left: 8rem;
            padding-top: 2rem;
            font-size: x-large;
            font-weight: bolder;
        }

        .form-container form {
            display: flex;
            flex-direction: column;
            gap: 0rem;
            padding: 1rem;
            font-family: 'Montserrat', sans-serif;

        }

        .form-group {
            display: flex;
            flex-direction: row;
            width: 100%;
            gap: 0rem;
            align-items: center;
            margin-bottom: 1.5rem;
            justify-content: space-between;
            flex-wrap: wrap;
        }

        .form-group label {
            margin-bottom: 0.5rem;
            font-weight: bold;
            font-size: 1.5rem;
        }

        .form-group input,
        .form-group textarea {
            padding: 0.75rem;
            font-size: 0.5rem;
            border: 1.5px solid #686060;
            border-radius: 8px;
            width: 100%;
            box-sizing: border-box;
        }

        textarea {
            resize: vertical;
            min-height: 100px;
        }

        .submit-buttons {
            align-items: center;
            margin: 1rem;
            width: 10rem;
            color: #D9D9D9;
            font-weight: bolder;
            font-size: xx-large;
            border-radius: 5px;
        }

        .btn-grp {
            display: flex;
            justify-content: right;
            margin-right: -1rem;
        }

        .submit-buttons:hover {
            background-color: rgb(137, 137, 137);
            color: black;
            cursor: pointer;
            font-weight: bolder;
        }
    </style>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light custom-navbar">
        <a class="navbar-brand" href="{{url_for('home')}}"><b>Hi, {{user_data.Full_Name}}</b></a>

        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link active" href="{{url_for('home')}}">Home</a>
                <a class="nav-item nav-link" href="{{url_for('user.user_summary')}}">Summary</a>
                <a class="nav-item nav-link" href="{{url_for('auth.logout')}}">Log out</a>
            </div>
            <a href="{{ url_for('user.user_profile')}}" class="btn btn-primary btn-sm">Edit Profile</a>
    </nav>
    <div class="container">
        <h1>Book the parking spot</h1>
    </div>
    <div class="form-container container">
        <form action="{{url_for('user.reserving',user_id=user_id,spot_id=spot_id)}}" method="POST">
            <div class="form-group">
                <label>Spot id: <br> </label>
                <input style="margin-left: 6.7rem;width: 50vw; font-size: large; " type="text" name="spot_id"
                    value="{{spot_id}}" readonly>
            </div>
            <div class="form-group">
                <label>Lot id: <br> </label>
                <input style="margin-left: 6.7rem;width: 50vw; font-size: large; " type="text" name="lot_id"
                    value="{{lot_id}}" readonly>
            </div>

            <div class="form-group">
                <label>User id:</label>
                <input style="margin-left: 16.5rem; width:50vw ;font-size: large;" type="text" name="user_id"
                    maxlength="6" value="{{user_id}}"  readonly>
            </div>
            <div class="form-group">
                <label>Vehicle no:</label>
                <input style="margin-left: 16.5rem; width:50vw ;font-size: large;" type="text" name="vehicle_no"
                  placeholder="vehicle no" >
            </div>
            <div class="btn-grp">
                <button class="btn-primary submit-buttons" type="submit">Book</button>
                <a class="btn-primary submit-buttons" href="{{url_for('home')}}"
                    style="text-decoration: none;">Cancel</a>
            </div>
        </form>
    </div>

</body>

</html>

parking_app_23f2005464/templates/edit_profile_user.html
<!DOCTYPE html>
<!DOCTYPE html>
<html>

<head>
    <title>Admin</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Londrina+Solid&display=swap">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
        rel="stylesheet">
    <style>
        .custom-navbar {
            background-color: #D9D9D9;
            font-family: "Inter", sans-serif;
        }

        .navbar-brand {
            color: black;
            margin-left: 1rem;
        }

        .navbar-nav {
            display: flex;
            justify-content: center;
            gap: 1rem;
            font-size: larger;
            margin-left: auto;
        }

        .nav-item.nav-link {
            padding-left: 50px !important;
        }

        .btn-primary {
            background: black;
            border-color: black;
            margin-left: auto;
            margin-right: 1rem;
        }

.btn-primary:hover {
    background-color: #048002;
    border-color: #222831;
}

       

        .container {
            height: fit-content;
            justify-content: center;
            border-style: solid;
            border-color: black;
            border-radius: 20px;
            margin-top: 2rem;
            text-align: center;
            overflow-y: auto;
            scrollbar-width: none;
        }

        .form-text {
            display: flex-box;
            max-width: max-content;
            padding-left: 8rem;
            padding-top: 2rem;
            font-size: x-large;
            font-weight: bolder;
        }

        .form-container form {
            display: flex;
            flex-direction: column;
            gap: 0rem;
            padding: 1rem;
            font-family: 'Montserrat', sans-serif;

        }

        .form-group {
            display: flex;
            flex-direction: row;
            width: 100%;
            gap: 0rem;
             align-items: center;
             margin-bottom: 1.5rem;
             justify-content: space-between;
             flex-wrap: wrap;
        }

        .form-group label {
            margin-bottom: 0.5rem;
            font-weight: bold;
            font-size: 1.5rem;
        }

        .form-group input,
        .form-group textarea {
            padding: 0.75rem;
            font-size: 0.5rem;
            border: 1.5px solid #686060;
            border-radius: 8px;
            width: 100%;
            box-sizing: border-box;
        }

        textarea {
            resize: vertical;
            min-height: 100px;
        }

        .submit-buttons {
            align-items: center;
            margin: 1rem ;
            width: 10rem;
            color: #D9D9D9;
            font-weight: bolder;
            font-size: xx-large;
            border-radius: 5px;
        }

        .btn-grp {
          display:flex;
          justify-content:right;
          margin-right:-1rem;
        }

        .submit-buttons:hover {
            background-color: rgb(137, 137, 137);
            color: black;
            cursor: pointer;
            font-weight: bolder;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light custom-navbar">
        <a class="navbar-brand" href="{{url_for('home')}}"><b>Hi, {{user_data.Full_Name}}</b></a>

        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link active" href="{{url_for('home')}}">Home</a>
                <a class="nav-item nav-link" href="{{url_for('user.user_summary')}}">Summary</a>
                <a class="nav-item nav-link" href="{{url_for('auth.logout')}}">Log out</a>
            </div>
            <a href="{{ url_for('user.user_profile')}}" class="btn btn-primary btn-sm">Edit Profile</a>
    </nav>
    <div class="container">
        <h1>Edit Profile</h1>
    </div>
    <div class="form-container container">
        <form action="{{url_for('user.user_edit',user_id=user.id)}}" method="POST">
            <div class="form-group">
                <label>Your Name : <br> </label>
                <input style="margin-left: 6.7rem;width: 50vw; font-size: large; " type="text" name="Name" value="{{user.Full_Name}}">
            </div>
            <div class="form-group">
                <label>Email : <br> </label>
                <input style="margin-left: 6.7rem;width: 50vw; font-size: large; " type="text" name="email" value="{{user.email}}" readonly>
            </div>
            <div class="form-group">
                <label>Address : </label>
                <textarea style="margin-left: 16rem; height:5rem ;width:50vw;text-wrap:initial;font-size: large;" type="text"
                    name="Address">{{user.Address}}</textarea>
            </div>
            <div class="form-group">
                <label>Pincode :</label>
                <input style="margin-left: 16.5rem; width:50vw ;font-size: large;" type="text" name="Pincode" maxlength="6" value="{{user.Pincode}}">
            </div>

            <div class="btn-grp">
                <button class="btn-primary submit-buttons" type="submit">Edit</button>
                <a class="btn-primary submit-buttons" href="{{url_for('home')}}" style="text-decoration: none;">Cancel</a>          
            </div>
        </form>
    </div>
    <!-- <script>
        window.onload =  function() {    
        var messages = {{ get_flashed_messages(with_categories=false)|tojson }}; //message is in python dict so we need to convert into json
        console.log(messages)
         if (messages.length > 0) {
         alert(messages.join('\n'));
         }
   
  }
    </script> -->
</body>
</html>

parking_app_23f2005464/templates/home.html
<!DOCTYPE html>
<html>

<head>
    <title> Home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Londrina+Solid&display=swap">
    <link rel="stylesheet" href="{{url_for('static',filename='home.css')}}">


</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light custom-navbar">
        <a class="navbar-brand" href="{{url_for('home')}}"><b>Hi, {{user_data.Full_Name}}</b></a>

        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link active" href="{{url_for('home')}}">Home</a>
                <a class="nav-item nav-link" href="{{url_for('user.user_summary')}}">Summary</a>
                <a class="nav-item nav-link" href="{{url_for('auth.logout')}}">Log out</a>
            </div>
            <a href="{{ url_for('user.user_profile')}}" class="btn btn-primary btn-sm">Edit Profile</a>
    </nav>
    <div class="search-bar">
        <h5>Search parking locations</h5>
        <form id="search-form" action="{{ url_for('user.search_lots')}}" method="POST">
            <input class="inside_container" id="pincode-input" name="pincode" type="text" pattern="^\d{6}"
                inputmode="numeric" maxlength="6" placeholder="Enter Pincode">
            <button type="submit" style="background-color:#ffffff ;  box-shadow: none; border: 1px solid #ffffff;">
                <img src="{{url_for('static',filename="download.png")}}" width="22px" class="clickable">
            </button>
        </form>
    </div>

    <div class="container container2" id="lot_cards">
        {% if not Searched_flag %}
        <h1 style="color:black;text-align:center ;margin-top:8rem">Parking Lots in your location #{{user_data.Pincode}}
        </h1>
        {% endif %}
        {% if lots %}
        {% for row in lots %}
        <div class="card mt-3">
            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Address</th>
                            <th>Availability</th>
                            <th>Price</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{ row.id }}</td>
                            <td>{{ row.Address }}</td>
                            <td>{{ row.Available_spots }}</td>
                            <td>{{ row.price }}</td>
                            <td><a href='{{url_for('user.booking_spot_form',lot_id=row.id)}}'class="btn btn-primary btn-sm" id='Buy-button'>Buy</a></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        {% endfor %}
        {% else %}
        {% endif %}
    </div>

    <div class="container">
        <h5>Recent Parking History</h3>
            <div class="lot_container_grp">
                <div class="grp" id="grp">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>spot id</th>
                                <th>vehicle number</th>
                                <th>Pincode</th>
                                <th>Address</th>
                                <th>Booked Time</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        {% if reserves %}
                        {% for reserve in reserves %}
                        <tbody>
                            <tr>
                                <td>{{reserve.spot_id}}</td>
                                <td>{{reserve.vehicle_number}}</td>
                                <td>{{reserve.parking_spot.parking_lot.Pincode}}</td>
                                <td>{{reserve.parking_spot.parking_lot.Address}}</td>
                                <td>{{get_ist_now(reserve.parking_timestamp)}}</td>
                                {% if reserve.end_parking_timestamp is none %}
                                <td><a href='{{ url_for("user.release_and_payment", spot_id=reserve.spot_id) }}'
                                        class="btn btn-primary btn-sm" id='release-btn'>Release</a></td>
                                {% else %}
                                <td><b> Parked Out</td>
                                {% endif%}
                            </tr>
                        </tbody>
                        {% endfor %}
                        {% endif %}
                    </table>
                </div>
            </div>
    </div>
    </div>
    </div>
    </div>

    </div>

</body>


</html>

parking_app_23f2005464/templates/success.html
<html>
<head>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Londrina+Solid&display=swap">
    <style>
        #container{
            display: flex;
            justify-content: center;
            align-items: center;
            height:100%;
            width: 100%;
        }
        
        
        #small-container{
            text-align: center;
            justify-content: center;
            align-items: center;
            background-color: #ffff;
            display: flex;
            flex-direction: column;
            height: 30vh;
            border: solid 2px;
            border-radius: 25px;
            box-shadow: 0px 5px 2px;
        }
        .ok-btn{
            margin-top: 1rem;
            padding: 0.5rem;
            padding-right:100px;
            padding-left: 100px;
            background-color: lawngreen;
            border-style: solid;
            border-radius: 5px;

            
        }
        .align-container{
            display: flex;
            width:max-content;
            justify-content: center;
            font-size:x-large;

        }
    </style>
</head>
<body>
    <div id='container'>
        <div id="small-container">
            <div class="align-container">
            <p><b>{{ message or "Success" }}</b></p>
            </div>
            <div class="align-container">
            <form action="{{ redirect_url }}" method="get">
                <button type="submit" class="ok-btn">OK</button>
            </form>
        </div>
        </div>
       
    </div>   

</body>
</html>